{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation-layout/1.9.0/foundation-layout-1.9.0.module",
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13900193"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout.aar",
          "url": "foundation-layout-android-1.9.0.aar",
          "size": 590371,
          "sha512": "c3929f37daadfc0259a276072ed22310c097a8d12e541d3354e58b2e3d6a31d6664ec6419d2069ebbe002df3b09182df8062a006425ae2c47ec12d5ad570d800",
          "sha256": "9354b415148840ccbaf216b53161ff2c55ccbec90a94d3466e5e573b4b41f34e",
          "sha1": "d543e5fbc28a0c7c842fdadffcc0cf1b368e1cbd",
          "md5": "bb2b089a4e0446fb1a48068832542f45"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout.aar",
          "url": "foundation-layout-android-1.9.0.aar",
          "size": 590371,
          "sha512": "c3929f37daadfc0259a276072ed22310c097a8d12e541d3354e58b2e3d6a31d6664ec6419d2069ebbe002df3b09182df8062a006425ae2c47ec12d5ad570d800",
          "sha256": "9354b415148840ccbaf216b53161ff2c55ccbec90a94d3466e5e573b4b41f34e",
          "sha1": "d543e5fbc28a0c7c842fdadffcc0cf1b368e1cbd",
          "md5": "bb2b089a4e0446fb1a48068832542f45"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-android-1.9.0-sources.jar",
          "url": "foundation-layout-android-1.9.0-sources.jar",
          "size": 108196,
          "sha512": "c2fd5384503111fea42fee04cdbabbed2b11640e5f6d2b2533e0e85696dd9f3d12aaea3073223e742db49e7b2f05251e7c1dae076e1935b431dc45de530293a6",
          "sha256": "0eb54d12eea32a1fdeb120417f7ea3f8def0e9707673bc752e2dab508b7023d8",
          "sha1": "59f899b03e2bc8e62b3d3cdfc1ecffab0efbcba7",
          "md5": "e528feee351fd492c656506d481da400"
        },
        {
          "name": "foundation-layout-1.9.0-samples-sources.jar",
          "url": "foundation-layout-android-1.9.0-samples-sources.jar",
          "size": 32462,
          "sha512": "e7b041cbea40e601edbf342cd3ade516841a076ab97f1158b1df9f58e4d5f5d5906bc42f7286e1dbf6ad302d69e277fe65cd7ba6cc4bbf487a65e3b9c9249264",
          "sha256": "0d6c4ce79232dd01c1d5321436598c5fcfad349f075b1bb655f420e0a8f745ba",
          "sha1": "d11ffc32b63523b42e060501814ca1b3c060c9f6",
          "md5": "ac6f89ae92fe8a65ef7cdf26b6ca0d98"
        }
      ]
    }
  ]
}