{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.9.0/foundation-1.9.0.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13900193"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "foundation-android-1.9.0.aar",
          "size": 5154110,
          "sha512": "9330c9f83fd2c086e335aa52a5811098c40bb4729a499475dfa9b1397010dfba51da6f5faddb8cc342f5d1058d14770ce606a1520645c9480f5af93378825470",
          "sha256": "691ba463d1e0a5b32d94f0448d692572faadf7a10a9c7460af41b2c430b36782",
          "sha1": "0b3222bb204d8e41afa22b25df0f22a3ac1c7212",
          "md5": "efaf7330df6786ce3f848e7166e068ca"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-release.aar",
          "url": "foundation-android-1.9.0.aar",
          "size": 5154110,
          "sha512": "9330c9f83fd2c086e335aa52a5811098c40bb4729a499475dfa9b1397010dfba51da6f5faddb8cc342f5d1058d14770ce606a1520645c9480f5af93378825470",
          "sha256": "691ba463d1e0a5b32d94f0448d692572faadf7a10a9c7460af41b2c430b36782",
          "sha1": "0b3222bb204d8e41afa22b25df0f22a3ac1c7212",
          "md5": "efaf7330df6786ce3f848e7166e068ca"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-1.9.0-samples-sources.jar",
          "url": "foundation-android-1.9.0-samples-sources.jar",
          "size": 87172,
          "sha512": "f6c6d56b83660a019e4df6edcacbd1503633990e8304262a14dfe6461f257aac525f8a5b3d2bfae498cab0410d5c1827a1fff79f74c4b0bcc6b470ee75f70549",
          "sha256": "9e80439b49c764cdcae2e74a1bba214a85fba0deaac672dd668a4eafcbfeda9f",
          "sha1": "927d417e21c50f15cd7f4a7c24433b7688d91f30",
          "md5": "e9cc244f25e0b12eb772bfbdc5bb9d14"
        },
        {
          "name": "foundation-android-1.9.0-sources.jar",
          "url": "foundation-android-1.9.0-sources.jar",
          "size": 1044820,
          "sha512": "42a1fdf6f135ee7556027e2d50111a2543fdd5914217c7af2dd4c37edab2a4bf6ebcc4f76f335b5fc843e5ff84c4a754e6a3e9c296a8ac79d701592c0a4f5fb3",
          "sha256": "d0e54de471b18a9259527613687ab454f7195e4a0f74f0ef09d6bfb814a53586",
          "sha1": "436659f3a22d079809c2caa3eaac043550e71e15",
          "md5": "842cd8714eb57407bb24afb9f3ee4152"
        }
      ]
    }
  ]
}